.TH UTOX 1 "September 2014"

.SH NAME
utox - lightweight GUI Tox client

.SH SYNOPSIS
.B utox

.SH DESCRIPTION
.B utox
is at the early stages of development but it currently supports
some of the most important features, such as file transfers, A/V, group chats,
and DNS Discovery

.SH OPTIONS
.BI utox
has no command line options.

.SH SEE ALSO
.br
.B Homepage:
https://github.com/notsecure/uTox
.br

.B Tox Wiki:
https://wiki.tox.im/UTox
.br

.SH AUTHOR
This manual page was written by kytv <killyourtv@i2pmail.org> for the Debian system (but may be used by others).
.br
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or any later version published by the Free Software Foundation
.br
On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.
